{% set name = "scikit-base" %}
{% set version = "0.9.0" %}

package:
  name: {{ name|lower }}-suite
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 9ff05e5488b6ebfa4def35769c6e71322ed678f14c62df2fbd15100f68cffdfb

build:
  noarch: python
  number: 0

requirements:
  host:
    - python >=3.7
  run:
    - python >=3.7


outputs:
  - name: {{ name|lower }}
    build:
      noarch: python
      script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --no-index --no-compile
    requirements:
      host:
        - python >=3.7,<3.13
        - pip
        - setuptools
      run:
        - python >=3.7,<3.13

    test:
      requires:
        - pip
        - pytest
        - numpy
        - scipy
        - pandas
        - scikit-learn>=0.24.0
      commands:
        - pip check
      imports:
        - skbase
        - skbase.base
        - skbase.lookup
        - skbase.testing
        - skbase.validate

  - name: {{ name|lower }}-all-extras
    build:
      noarch: python
    requirements:
      host:
        - python >=3.7,<3.13
      run:
        - python >=3.7,<3.13
        - {{ pin_subpackage("scikit-base", exact=True) }}
        - pandas
        - numpy

    test:
      imports:
        - skbase
        - skbase.base
        - skbase.lookup
        - skbase.testing
        - skbase.validate
      commands:
        - pip check
      requires:
        - pip
        - pytest
        - numpy
        - scipy
        - pandas
        - scikit-learn>=0.24.0

about:
  home: https://github.com/sktime/skbase
  summary: Base classes for sklearn-like parametric objects
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  doc_url: https://skbase.readthedocs.io/en/latest/
  dev_url: https://github.com/sktime/skbase

extra:
  recipe-maintainers:
    - mcre-be
    - dhirschfeld
    - yarnabrina
    - fkiraly
