{% set name = "scikit-base" %}
{% set version = "0.7.5" %}

package:
  name: {{ name|lower }}-suite
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7ee00cef4b188fd3694d3a6e82a20ab8b4cc21cb59c758eff6a653905472003b

build:
  number: 0
  skip: true  # [(py==37 and aarch64)]
  skip: true  # [py<37 or py>311]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
  run:
    - python

outputs:
  - name: {{ name|lower }}
    script: build_script.sh  # [unix]
    script: build_script.bat  # [win]
    requirements:
      build:
        - python                                 # [build_platform != target_platform]
        - cross-python_{{ target_platform }}     # [build_platform != target_platform]
      host:
        - python
        - pip
        - setuptools
      run:
        - python >=3.7,<3.12

    test:
      requires:
        - pip
        - pytest
        - numpy
        - scipy
        - pandas
        - scikit-learn>=0.24.0
      commands:
        - pip check
      imports:
        - skbase
        - skbase.base
        - skbase.lookup
        - skbase.testing
        - skbase.validate

  - name: {{ name|lower }}-all-extras
    build:
      #FIXME: Extras environment not resolvable on aarch. Needs someone with
      #arm machine to tests.
      skip: true  # [aarch64]
      noarch: python
    requirements:
      host:
        - python
        - pip
        - setuptools
      run:
        - python >=3.7,<3.12
        - {{ pin_subpackage("scikit-base", exact=True) }}
        - pandas
        - numpy

    test:
      imports:
        - skbase
        - skbase.base
        - skbase.lookup
        - skbase.testing
        - skbase.validate
      commands:
        - pip check
      requires:
        - pip
        - pytest
        - numpy
        - scipy
        - pandas
        - scikit-learn>=0.24.0

about:
  home: https://github.com/sktime/skbase
  summary: Base classes for sklearn-like parametric objects
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  doc_url: https://skbase.readthedocs.io/en/latest/
  dev_url: https://github.com/sktime/skbase

extra:
  recipe-maintainers:
    - yarnabrina
    - fkiraly
    - RNKuhns
